### PR TITLE
Redirect user to override path when already logged in

### LINKED ISSUE #16: Redirect to particular page when already logged in
If a user is already logged in, the login form will redirect them.  We want this action to also respect the `?redirect=` querystring parameter.

1. Visit `/login?redirect=/path` while logged in

What should happen: should redirect the user to `/path`

### PR DESCRIPTION
**Pull request by damionvega**
Closes #16

### CODE REVIEW

**Review by tyrw — APPROVED** [review]
I like the `__get__` and `__set__` pattern for mocking 👍

**Comment by damionvega** [comment]
Yeah it's a lot of noise though, was thinking of making a wrapper function for it. Something like:

```js
    // Before
    Userfront.__set__("removeAllCookies", jest.fn());
    Userfront.removeAllCookies = Userfront.__get__("removeAllCookies");

    // After
    Userfront.removeAllCookies = mockModuleFn(Userfront, "removeAllCookies");
    Userfront.removeAllCookies // Jest mock function
 ```

but then can see it getting messy in the future with other functions to track and reset mocks, etc. so may be better to just leave unambiguous.

**Comment by tyrw** [comment]
I'm refactoring in a branch I'm working on, and as clever as it is, I don't think we'll need to use it much.

Essentially we want to delineate between what is exported by a file vs what is exported by the whole library.  We can export all we want from various utility files and import those for testing, and only export the few things we have documented for the `Userfront` object.

**Comment by tyrw** [comment]
Refactored PR is not quite ready yet, but you can view it here if you want https://github.com/userfront/userfront-core/pull/18/files

**Pull request merged**
